CREATE TABLE user (
    id INTEGER IDENTITY PRIMARY KEY ,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created BIGINT NOT NULL,
    updated BIGINT NOT NULL,
);